/* 수강신청 */
DROP TABLE SUB_APPLS 
	CASCADE CONSTRAINTS;

/* 과정 */
DROP TABLE SUBJECTS 
	CASCADE CONSTRAINTS;

/* 강사 */
DROP TABLE TEACHERS 
	CASCADE CONSTRAINTS;

/* 학생 */
DROP TABLE STUDENTS 
	CASCADE CONSTRAINTS;

/* 강사강의과목 */
DROP TABLE TEACH_SUBJ 
	CASCADE CONSTRAINTS;

/* 주소 */
DROP TABLE ADDRS 
	CASCADE CONSTRAINTS;

/* 수강신청 */
CREATE TABLE SUB_APPLS (
	SANO INTEGER NOT NULL, /* 수강신청번호 */
	SNO INTEGER NOT NULL, /* 과정일련번호 */
	EMAIL VARCHAR2(40) NOT NULL, /* 학생이메일 */
	APPRV INTEGER DEFAULT 0 /* 합격여부 */
);

COMMENT ON TABLE SUB_APPLS IS '수강신청';

COMMENT ON COLUMN SUB_APPLS.SANO IS '수강신청번호';

COMMENT ON COLUMN SUB_APPLS.SNO IS '과정일련번호';

COMMENT ON COLUMN SUB_APPLS.EMAIL IS '학생이메일';

COMMENT ON COLUMN SUB_APPLS.APPRV IS '합격여부';

CREATE UNIQUE INDEX PK_SUB_APPLS
	ON SUB_APPLS (
		SANO ASC
	);

CREATE UNIQUE INDEX UIX_SUB_APPLS
	ON SUB_APPLS (
		SNO ASC,
		EMAIL ASC
	);

ALTER TABLE SUB_APPLS
	ADD
		CONSTRAINT PK_SUB_APPLS
		PRIMARY KEY (
			SANO
		);

ALTER TABLE SUB_APPLS
	ADD
		CONSTRAINT UK_SUB_APPLS
		UNIQUE (
			SNO,
			EMAIL
		);

/* 과정 */
CREATE TABLE SUBJECTS (
	SNO INTEGER NOT NULL, /* 과정일련번호 */
	TITLE VARCHAR2(255) NOT NULL, /* 과정명 */
	CONTENTS CLOB NOT NULL, /* 과정내용 */
	ST_DT DATE NOT NULL, /* 시작일 */
	ED_DT DATE NOT NULL, /* 종료일 */
	LOC VARCHAR2(30), /* 교육장 */
	ROOM VARCHAR2(30), /* 강의실 */
	PRICE INTEGER /* 수강료 */
);

COMMENT ON TABLE SUBJECTS IS '과정';

COMMENT ON COLUMN SUBJECTS.SNO IS '과정일련번호';

COMMENT ON COLUMN SUBJECTS.TITLE IS '과정명';

COMMENT ON COLUMN SUBJECTS.CONTENTS IS '과정내용';

COMMENT ON COLUMN SUBJECTS.ST_DT IS '시작일';

COMMENT ON COLUMN SUBJECTS.ED_DT IS '종료일';

COMMENT ON COLUMN SUBJECTS.LOC IS '교육장';

COMMENT ON COLUMN SUBJECTS.ROOM IS '강의실';

COMMENT ON COLUMN SUBJECTS.PRICE IS '수강료';

CREATE UNIQUE INDEX PK_SUBJECTS
	ON SUBJECTS (
		SNO ASC
	);

CREATE INDEX IX_SUBJECTS
	ON SUBJECTS (
		TITLE ASC
	);

ALTER TABLE SUBJECTS
	ADD
		CONSTRAINT PK_SUBJECTS
		PRIMARY KEY (
			SNO
		);

/* 강사 */
CREATE TABLE TEACHERS (
	EMAIL VARCHAR2(40) NOT NULL, /* 이메일 */
	NAME VARCHAR2(30) NOT NULL, /* 강사명 */
	TEL VARCHAR2(30) NOT NULL, /* 전화 */
	PHOTO VARCHAR2(255) DEFAULT 'default.png' /* 사진 */
);

COMMENT ON TABLE TEACHERS IS '강사';

COMMENT ON COLUMN TEACHERS.EMAIL IS '이메일';

COMMENT ON COLUMN TEACHERS.NAME IS '강사명';

COMMENT ON COLUMN TEACHERS.TEL IS '전화';

COMMENT ON COLUMN TEACHERS.PHOTO IS '사진';

CREATE UNIQUE INDEX PK_TEACHERS
	ON TEACHERS (
		EMAIL ASC
	);

CREATE UNIQUE INDEX UIX_TEACHERS
	ON TEACHERS (
		TEL ASC
	);

CREATE INDEX IX_TEACHERS
	ON TEACHERS (
		NAME ASC
	);

ALTER TABLE TEACHERS
	ADD
		CONSTRAINT PK_TEACHERS
		PRIMARY KEY (
			EMAIL
		);

ALTER TABLE TEACHERS
	ADD
		CONSTRAINT UK_TEACHERS
		UNIQUE (
			TEL
		);

/* 학생 */
CREATE TABLE STUDENTS (
	EMAIL VARCHAR2(40) NOT NULL, /* 이메일 */
	NAME VARCHAR2(30) NOT NULL, /* 학생명 */
	TEL VARCHAR2(30) NOT NULL, /* 전화 */
	PHOTO VARCHAR2(255) DEFAULT 'default.png', /* 사진 */
	WORK INTEGER NOT NULL, /* 재직여부 */
	LAST_SCH VARCHAR2(30) NOT NULL, /* 최종학력 */
	SCHOOL VARCHAR2(30), /* 최종학교 */
	POSTNO CHAR(5), /* 우편번호 */
	DET_ADDR VARCHAR2(255) /* 상세주소 */
);

COMMENT ON TABLE STUDENTS IS '학생';

COMMENT ON COLUMN STUDENTS.EMAIL IS '이메일';

COMMENT ON COLUMN STUDENTS.NAME IS '학생명';

COMMENT ON COLUMN STUDENTS.TEL IS '전화';

COMMENT ON COLUMN STUDENTS.PHOTO IS '사진';

COMMENT ON COLUMN STUDENTS.WORK IS '재직여부';

COMMENT ON COLUMN STUDENTS.LAST_SCH IS '최종학력';

COMMENT ON COLUMN STUDENTS.SCHOOL IS '최종학교';

COMMENT ON COLUMN STUDENTS.POSTNO IS '우편번호';

COMMENT ON COLUMN STUDENTS.DET_ADDR IS '상세주소';

CREATE UNIQUE INDEX PK_STUDENTS
	ON STUDENTS (
		EMAIL ASC
	);

CREATE UNIQUE INDEX UIX_STUDENTS
	ON STUDENTS (
		TEL ASC
	);

CREATE INDEX IX_STUDENTS
	ON STUDENTS (
		NAME ASC
	);

ALTER TABLE STUDENTS
	ADD
		CONSTRAINT PK_STUDENTS
		PRIMARY KEY (
			EMAIL
		);

ALTER TABLE STUDENTS
	ADD
		CONSTRAINT UK_STUDENTS
		UNIQUE (
			TEL
		);

/* 강사강의과목 */
CREATE TABLE TEACH_SUBJ (
	SNO INTEGER NOT NULL, /* 과정일련번호 */
	EMAIL VARCHAR2(40) NOT NULL /* 이메일 */
);

COMMENT ON TABLE TEACH_SUBJ IS '강사강의과목';

COMMENT ON COLUMN TEACH_SUBJ.SNO IS '과정일련번호';

COMMENT ON COLUMN TEACH_SUBJ.EMAIL IS '이메일';

CREATE UNIQUE INDEX PK_TEACH_SUBJ
	ON TEACH_SUBJ (
		SNO ASC,
		EMAIL ASC
	);

ALTER TABLE TEACH_SUBJ
	ADD
		CONSTRAINT PK_TEACH_SUBJ
		PRIMARY KEY (
			SNO,
			EMAIL
		);

/* 주소 */
CREATE TABLE ADDRS (
	POSTNO CHAR(5) NOT NULL, /* 우편번호 */
	BAS_ADDR VARCHAR2(255) NOT NULL /* 기본주소 */
);

COMMENT ON TABLE ADDRS IS '주소';

COMMENT ON COLUMN ADDRS.POSTNO IS '우편번호';

COMMENT ON COLUMN ADDRS.BAS_ADDR IS '기본주소';

CREATE UNIQUE INDEX PK_ADDRS
	ON ADDRS (
		POSTNO ASC
	);

ALTER TABLE ADDRS
	ADD
		CONSTRAINT PK_ADDRS
		PRIMARY KEY (
			POSTNO
		);

ALTER TABLE SUB_APPLS
	ADD
		CONSTRAINT FK_SUBJECTS_TO_SUB_APPLS
		FOREIGN KEY (
			SNO
		)
		REFERENCES SUBJECTS (
			SNO
		);

ALTER TABLE SUB_APPLS
	ADD
		CONSTRAINT FK_STUDENTS_TO_SUB_APPLS
		FOREIGN KEY (
			EMAIL
		)
		REFERENCES STUDENTS (
			EMAIL
		);

ALTER TABLE STUDENTS
	ADD
		CONSTRAINT FK_ADDRS_TO_STUDENTS
		FOREIGN KEY (
			POSTNO
		)
		REFERENCES ADDRS (
			POSTNO
		);

ALTER TABLE TEACH_SUBJ
	ADD
		CONSTRAINT FK_SUBJECTS_TO_TEACH_SUBJ
		FOREIGN KEY (
			SNO
		)
		REFERENCES SUBJECTS (
			SNO
		);

ALTER TABLE TEACH_SUBJ
	ADD
		CONSTRAINT FK_TEACHERS_TO_TEACH_SUBJ
		FOREIGN KEY (
			EMAIL
		)
		REFERENCES TEACHERS (
			EMAIL
		);